apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment99
  labels:
    app: nginx99
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx99
  template:
    metadata:
      labels:
        app: nginx99
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80