apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment3
  labels:
    app: nginx3
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment4
  labels:
    app: nginx4
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx4
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment5
  labels:
    app: nginx5
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx5
  template:
    metadata:
      labels:
        app: nginx5
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment6
  labels:
    app: nginx6
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx6
  template:
    metadata:
      labels:
        app: nginx6
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment7
  labels:
    app: nginx7
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx7
  template:
    metadata:
      labels:
        app: nginx7
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment8
  labels:
    app: nginx8
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx8
  template:
    metadata:
      labels:
        app: nginx8
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment9
  labels:
    app: nginx9
spec:
  replicas: 1
  selector:
    matchLabels:
          app: nginx9
  template:
    metadata:
      labels:
        app: nginx9
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "10Mi"
        ports:
        - containerPort: 80


---
