kind: Service 
apiVersion: v1 
metadata:
  name: ksm-mock 
  namespace: ksm
spec:

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # replaced with test
  selector:
    app: ksm-mock

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 8080 
      targetPort: 80