apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ing
  namespace: monitoring 
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus-dashboard.com
    http:
      paths:
      - backend:
          service:
            name: prometheus-server
            port:
              number: 80
        pathType: Prefix
        path: /
  - host: grafana-dashboard.com
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 80
        pathType: Prefix
        path: /